#pragma once

#define BALL_RADIUS 20
#define BALL_VELOCITY_INITIAL 10

#define MIDLINE_SUBSECT_LENGTH 20

#define PADDLE_HEIGHT 100
#define PADDLE_VELOCITY 20
#define PADDLE_WIDTH 20

#define SCORE_FONT_SIZE 100

#define SCREEN_HEIGHT 720
#define SCREEN_WIDTH 1280
